server:
  port: 8781

spring:
  application:
    name: @pom.artifactId@              # 指定注册到Eureka Server上的应用名称
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/mingwei-cheng/SpringCloud.git
          searchPaths: SpringCloud      
eureka:
  instance:
    hostname: xpoll
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true             # 将自己的IP注册到Eureka Server。若不配置或设置为false，表示注册微服务所在操作系统的hostname到Eureka Server
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: http://root:root@xpoll-eureka1:8761/eureka,http://root:root@xpoll-eureka2:8762/eureka,http://root:root@xpoll-eureka3:8763/eureka # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
    enabled: true
    register-with-eureka: true # 是否将自己注册到Eureka Server
    fetch-registry: true # 表示是否从Eureka Sever获取注册信息

    