server:
  port: 8762

spring:
  application:
    name: xpoll-cloud-eureka-server
  security:
    user:
      name: root
      password: root
    
eureka:
  instance:
    hostname: xpoll-eureka2
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@xpoll-eureka1:8761/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@xpoll-eureka3:8763/eureka/ # three eureka server
  server:
      waitTimeInMsWhenSyncEmpty: 0
      enableSelfPreservation: false
      